version: "2"

services:
  web:
    image: nginx:1.15.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"

    volumes:
      - ./app:/www
      - ./config:/etc/nginx/conf.d/default.conf

    links:
      - php
      
  php:
    build: .
    container_name: php-fpm
    volumes:
      - ./app:/www